security:
    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\Usuario

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern:    ^/
            logout:
                path:     /logout
            guard:
                authenticators:
                    - App\Security\FormAuthenticator
                    - App\Security\TokenAuthenticator
                entry_point: App\Security\FormAuthenticator
            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, role: IS_AUTHENTICATED_FULLY }
