default:
    resource: "routes/default.yaml"

security:
    resource: "routes/security.yaml"

usuario:
    resource: "routes/usuario.yaml"
    prefix: /usuarios

partido_usuario:
    resource: "routes/partido_usuario.yaml"
    prefix: /partidos